version: '3.7'

services:
  verdaccio:
    build:
      context: .
      args:
        - VERDACCIO_TAG=4.1
    ports:
      - 4873:4873
    depends_on:
      - minio
    environment:
      VERDACCIO_PROTOCOL: http
      VERDACCIO_PORT: 4873

  minio:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    command: server /data
    volumes:
      - minio:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: this-is-not-so-secret
      MINIO_SECRET_KEY: this-is-not-so-secret

volumes:
  minio:
