#!/bin/bash

PWD=$(pwd)
RED=$(tput -Txterm setaf 1)
GREEN=$(tput -Txterm setaf 2)
UNDERLINE="$(tput smul)"
NORMAL="$(tput sgr0)"
BOLD="$(tput bold)"

title() {
  echo "${UNDERLINE}${BOLD}${1}${NORMAL}"
}

success() {
  echo "${GREEN}✓${NORMAL} ${1}"
}

error() {
  echo "${RED}✗${NORMAL} $1"
  STATUS=1
}

panic() {
  printf "\n\n\t%s\n\n" "$1"
  exit 1
}

title "Building module"
{
  yarn build >/dev/null 2>&1
} || {
  panic "Failed to build module, try running 'yarn build' for detail"
}

title "Copying build result to example folder"
mkdir -p ./example/verdaccio-minio-storage
cp package.json ./example/verdaccio-minio-storage
cp -R lib ./example/verdaccio-minio-storage

title "Starting containers"
cd example
docker-compose up --build --force-recreate --remove-orphans
cd $PWD
