#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
MODE=""

source "$DIR/util"

pull() {
  title "Pulling from git to make sure we're up to date"
  {
    git pull
  } || {
    panic "Failed to pull latest changes from git"
  }
}

bump() {
  title "Publishing a new version using yarn"
  {
    if [ "$MODE" == "major" ]; then
      yarn publish --major
    elif [ "$MODE" == "minor" ]; then
      yarn publish --minor
    elif [ "$MODE" == "patch" ]; then
      yarn publish --patch
    else
      yarn publish
    fi
  } || {
    panic "Failed to publish package"
  }
}

push() {
  title "Pushing tag to origin"
  {
    git push --tags
  } || {
    panic "Failed to push tag to git"
  }
}

image() {
  title "Build & push docker image"
  {
    VERSION=$(node -p "require('./package.json').version")
    docker build --no-cache -t "barolab/verdaccio:$VERSION" .
    docker tag "barolab/verdaccio:$VERSION" "barolab/verdaccio:latest"

    docker push "barolab/verdaccio:$VERSION"
    docker push "barolab/verdaccio:latest"
  } || {
    panic "Failed to push new Docker image"
  }
}

release() {
  pull
  build
  bump
  push
  image
}

while [ "$1" != "" ]; do
  case $1 in
  --major)
    MODE="major"
    ;;
  --minor)
    MODE="minor"
    ;;
  --patch)
    MODE="patch"
    ;;
  esac
  shift
done

while true; do
    read -p "You're about to create a new ${MODE} version, did you updated the CHANGELOG ? (y/n)" yn
    case $yn in
        [Yy]* ) release; break;;
        [Nn]* ) echo "Yep, you forgot it..."; exit;;
        * ) echo "Please answer yes (y) or no (n).";;
    esac
done
